name: Linting

on:
  push:
  pull_request:
    types: [ opened, reopened, ready_for_review, synchronize, edited ]

jobs:

  check-linting:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: lint_requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lint_requirements.txt

      - name: Check isort
        uses: jamescurtin/isort-action@master

      - name: Check flake8
        run: flake8 .

      - name: Check black
        uses: psf/black@stable